[pytest]
addopts = -q --disable-warnings --maxfail=1 --html=reports/html/report.html --self-contained-html --headed
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
--html=reports/html/report.html --self-contained-html