class SidebarIDs:
    ROOM_VIEW_MENU = "sidebar__room_view__menu"
    STAY_VIEW_MENU = "sidebar__stay_view__menu"
    ALL_CHECKINS_MENU = "sidebar__all_checkins__menu"
    RESERVATIONS_MENU = "sidebar__reservations__menu"
    FOOD_MENU = "sidebar__food__menu"
    LEDGER_MENU = "sidebar__ledger__menu"
    FOLIO_MENU = "sidebar__folio__menu"
    INVENTORY_MENU = "sidebar__inventory__menu"
    BUSINESS_INTELLIGENCE_MENU = "sidebar__business_intelligence__menu"
    REPORTS_MENU = "sidebar__reports__menu"
    CHATS_MENU = "sidebar__chats__menu"
    SUPPORT_MENU = "sidebar__support__menu"
    SETTINGS_MENU = "sidebar__settings__menu"